"""Pydantic models for DOCX document structure.

This module provides type-safe models representing the structure of DOCX documents,
including document content, styles, and numbering definitions.
"""

# Re-export common models
from models.common import (
    Border,
    Color,
    Indentation,
    ParagraphBorders,
    Shading,
    Spacing,
    TableBorders,
    Width,
)

# Re-export document models
from models.document import (
    Body,
    BookmarkEnd,
    BookmarkStart,
    Break,
    CarriageReturn,
    Column,
    Columns,
    Document,
    DocumentGrid,
    EndnoteReference,
    FieldChar,
    FootnoteReference,
    FrameProperties,
    HeaderFooterReference,
    Hyperlink,
    InstrText,
    Language,
    LineNumberType,
    NoBreakHyphen,
    NumberingProperties,
    PageBorders,
    PageMargins,
    PageNumberType,
    PageSize,
    Paragraph,
    ParagraphProperties,
    Run,
    RunContentItem,
    RunFonts,
    RunProperties,
    SectionProperties,
    SoftHyphen,
    Symbol,
    TabChar,
    Table,
    TableCell,
    TableCellMargins,
    TableCellProperties,
    TableGrid,
    TableGridColumn,
    TableLook,
    TableProperties,
    TableRow,
    TableRowHeight,
    TableRowProperties,
    TabStop,
    Text,
    Underline,
)

# Re-export numbering models
from models.numbering import (
    AbstractNumbering,
    Level,
    LevelOverride,
    Numbering,
    NumberingInstance,
)

# Re-export style models
from models.styles import (
    DocumentDefaults,
    LatentStyleException,
    LatentStyles,
    ParagraphPropertiesDefault,
    RunPropertiesDefault,
    Style,
    Styles,
    TableStyleProperties,
)

__all__ = [
    # Common
    "Border",
    "Color",
    "Indentation",
    "ParagraphBorders",
    "Shading",
    "Spacing",
    "TableBorders",
    "Width",
    # Document
    "Document",
    "Body",
    "Paragraph",
    "ParagraphProperties",
    "NumberingProperties",
    "TabStop",
    "FrameProperties",
    "Hyperlink",
    "BookmarkStart",
    "BookmarkEnd",
    "Run",
    "RunProperties",
    "RunFonts",
    "Language",
    "Underline",
    "Text",
    "Break",
    "TabChar",
    "CarriageReturn",
    "SoftHyphen",
    "NoBreakHyphen",
    "Symbol",
    "FieldChar",
    "InstrText",
    "FootnoteReference",
    "EndnoteReference",
    "RunContentItem",
    "SectionProperties",
    "PageSize",
    "PageMargins",
    "Column",
    "Columns",
    "DocumentGrid",
    "HeaderFooterReference",
    "PageBorders",
    "PageNumberType",
    "LineNumberType",
    "Table",
    "TableProperties",
    "TableGrid",
    "TableGridColumn",
    "TableLook",
    "TableRow",
    "TableRowProperties",
    "TableRowHeight",
    "TableCell",
    "TableCellProperties",
    "TableCellMargins",
    # Styles
    "Styles",
    "Style",
    "DocumentDefaults",
    "RunPropertiesDefault",
    "ParagraphPropertiesDefault",
    "LatentStyles",
    "LatentStyleException",
    "TableStyleProperties",
    # Numbering
    "Numbering",
    "AbstractNumbering",
    "Level",
    "LevelOverride",
    "NumberingInstance",
]
